# Generated by Django 5.2.5 on 2025-08-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='test',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('POP', 'Pop'), ('Lydia', 'Lydia')], default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='genre',
            field=models.CharField(choices=[('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('POP', 'Pop'), ('Lydia', 'Lydia')], max_length=5),
        ),
    ]
