# Generated by Django 5.2.5 on 2025-08-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_test_alter_band_genre_alter_listing_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='test',
        ),
    ]
